name: cafe_booking

volumes:
  pg_data:

services:
  db:
    container_name: cafe-db
    image: postgres:17-alpine
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
  backend:
    container_name: cafe-back
    build:
      context: ../src
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
  gateway:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/templates/default.conf.template:ro
    env_file:
      - .env
    ports:
      - 8000:80
    depends_on:
      - db
      - backend
