"""First migrations

Revision ID: 3b3022e33b8d
Revises: 
Create Date: 2025-12-18 19:33:18.241038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b3022e33b8d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('null'), nullable=True),
    sa.Column('file_path', sa.String(length=2048), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_table('cafe',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('photo_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['media.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'address', name='uq_cafe_name_address')
    )
    op.create_index(op.f('ix_cafe_address'), 'cafe', ['address'], unique=False)
    op.create_index(op.f('ix_cafe_id'), 'cafe', ['id'], unique=False)
    op.create_index(op.f('ix_cafe_name'), 'cafe', ['name'], unique=False)
    op.create_index(op.f('ix_cafe_phone'), 'cafe', ['phone'], unique=False)
    op.create_table('slot',
    sa.Column('cafe_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('start_time < end_time', name='check_slot_time_range'),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafe.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cafe_id', 'start_time', 'end_time', name='unique_cafe_slot_time')
    )
    op.create_index(op.f('ix_slot_cafe_id'), 'slot', ['cafe_id'], unique=False)
    op.create_index(op.f('ix_slot_id'), 'slot', ['id'], unique=False)
    op.create_table('table',
    sa.Column('cafe_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('seat_number BETWEEN 1 AND 24', name='check_seat_number_range'),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafe.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_cafe_id'), 'table', ['cafe_id'], unique=False)
    op.create_index(op.f('ix_table_id'), 'table', ['id'], unique=False)
    op.create_table('user',
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('tg_id', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'USER', name='user_role_enum'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('cafe_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('(email IS NOT NULL) OR (phone IS NOT NULL)', name='check_user_email_or_phone_required'),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafe.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_table_id'), table_name='table')
    op.drop_index(op.f('ix_table_cafe_id'), table_name='table')
    op.drop_table('table')
    op.drop_index(op.f('ix_slot_id'), table_name='slot')
    op.drop_index(op.f('ix_slot_cafe_id'), table_name='slot')
    op.drop_table('slot')
    op.drop_index(op.f('ix_cafe_phone'), table_name='cafe')
    op.drop_index(op.f('ix_cafe_name'), table_name='cafe')
    op.drop_index(op.f('ix_cafe_id'), table_name='cafe')
    op.drop_index(op.f('ix_cafe_address'), table_name='cafe')
    op.drop_table('cafe')
    op.drop_table('media')
    # ### end Alembic commands ###
