"""Change field for model Table

Revision ID: 72c9d11a8d11
Revises: a5f1fddd0415
Create Date: 2026-01-11 21:10:18.054878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72c9d11a8d11'
down_revision: Union[str, Sequence[str], None] = 'a5f1fddd0415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table', sa.Column('seats_count', sa.Integer(), nullable=False))
    op.drop_column('table', 'seat_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table', sa.Column('seat_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('table', 'seats_count')
    # ### end Alembic commands ###
