"""First migrations

Revision ID: c67460b5106f
Revises: 
Create Date: 2026-01-14 20:17:31.083983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c67460b5106f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cafe',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=12), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('photo_id', sa.UUID(), nullable=True, comment='Идентификатор изображения в файловой системе'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'address', name='uq_cafe_name_address')
    )
    op.create_index(op.f('ix_cafe_address'), 'cafe', ['address'], unique=False)
    op.create_index(op.f('ix_cafe_id'), 'cafe', ['id'], unique=False)
    op.create_index(op.f('ix_cafe_name'), 'cafe', ['name'], unique=False)
    op.create_index(op.f('ix_cafe_phone'), 'cafe', ['phone'], unique=False)
    op.create_table('slot',
    sa.Column('cafe_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('start_time < end_time', name='check_slot_time_range'),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafe.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cafe_id', 'start_time', 'end_time', name='unique_cafe_slot_time')
    )
    op.create_index(op.f('ix_slot_cafe_id'), 'slot', ['cafe_id'], unique=False)
    op.create_index(op.f('ix_slot_id'), 'slot', ['id'], unique=False)
    op.create_table('table',
    sa.Column('cafe_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('seats_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('seats_count BETWEEN 1 AND 24', name='check_seats_count_range'),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafe.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_cafe_id'), 'table', ['cafe_id'], unique=False)
    op.create_index(op.f('ix_table_id'), 'table', ['id'], unique=False)
    op.create_table('user',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('tg_id', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'USER', name='user_role_enum'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('cafe_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('(email IS NOT NULL) OR (phone IS NOT NULL)', name='check_user_email_or_phone_required'),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafe.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('booking',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cafe_id', sa.Integer(), nullable=False),
    sa.Column('guest_number', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', name='booking_status_enum'), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('reminder_task_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('booking_date >= CURRENT_DATE', name='check_booking_date_not_past'),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafe.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_id'), 'booking', ['id'], unique=False)
    op.create_table('tableslotbooking',
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['slot_id'], ['slot.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'slot_id', 'booking_id', name='uq_table_slot_booking')
    )
    op.create_index(op.f('ix_tableslotbooking_id'), 'tableslotbooking', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tableslotbooking_id'), table_name='tableslotbooking')
    op.drop_table('tableslotbooking')
    op.drop_index(op.f('ix_booking_id'), table_name='booking')
    op.drop_table('booking')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_table_id'), table_name='table')
    op.drop_index(op.f('ix_table_cafe_id'), table_name='table')
    op.drop_table('table')
    op.drop_index(op.f('ix_slot_id'), table_name='slot')
    op.drop_index(op.f('ix_slot_cafe_id'), table_name='slot')
    op.drop_table('slot')
    op.drop_index(op.f('ix_cafe_phone'), table_name='cafe')
    op.drop_index(op.f('ix_cafe_name'), table_name='cafe')
    op.drop_index(op.f('ix_cafe_id'), table_name='cafe')
    op.drop_index(op.f('ix_cafe_address'), table_name='cafe')
    op.drop_table('cafe')
    # ### end Alembic commands ###
