from pathlib import Path

BASE_DIR = Path(__file__).resolve().parents[3]
INFRA_DIR = BASE_DIR / 'infra'

DEFAULT_LOCAL_HOST = 'localhost'
ENV_RUN_IN_DOCKER = 'RUN_IN_DOCKER'
TRUE_VALUE = 'yes'

MAX_LENGTH_USER_USERNAME = 150
MAX_LENGTH_USER_EMAIL = 255
MAX_LENGTH_USER_PHONE = 50
MAX_LENGTH_USER_PASSWORD_HASH = 255
MAX_LENGTH_USER_TG_ID = 50
MIN_LENGTH_USER_PASSWORD = 6
