from pathlib import Path

BASE_DIR = Path(__file__).resolve().parents[3]
INFRA_DIR = BASE_DIR / 'infra'

# --- Docker ---
DEFAULT_LOCAL_HOST = 'localhost'
ENV_RUN_IN_DOCKER = 'RUN_IN_DOCKER'
TRUE_VALUE = 'yes'

# --- Логирование ---
LOGS_DIR = Path('logs')
LOG_FILE = LOGS_DIR / 'app.log'
LOG_MAX_BYTES = 10 * 1024 * 1024  # 10 МБ
LOG_BACKUP_COUNT = 10

# --- User ---
ROLE_ADMIN = 'admin'
ROLE_MANAGER = 'manager'
ROLE_USER = 'user'
MAX_LENGTH_USER_USERNAME = 150
MAX_LENGTH_USER_EMAIL = 255
MAX_LENGTH_USER_PHONE = 50
MAX_LENGTH_USER_PASSWORD_HASH = 255
MAX_LENGTH_USER_TG_ID = 50
MIN_LENGTH_USER_PASSWORD = 6

# --- Slot ---
MAX_LENGTH_SLOT_DESCRIPTION = 255

# --- Cafe ---
MAX_LENGTH_CAFE_NAME = 255
MAX_LENGTH_CAFE_ADDRESS = 500
MAX_LENGTH_CAFE_PHONE = 50
MAX_LENGTH_CAFE_DESCRIPTION = 2000
MAX_LENGTH_UUID = 36

# --- Table ---
MIN_SEATS_NUMBER = 1
MAX_SEATS_NUMBER = 24

# ---Media ---
MAX_LENGTH_MEDIA_FILEPATH = 2048
MEDIA_PATH_DISPLAY_LENGTH = 60
