from pathlib import Path

BASE_DIR = Path(__file__).resolve().parents[3]
INFRA_DIR = BASE_DIR / 'infra'

DEFAULT_LOCAL_HOST = 'localhost'
ENV_RUN_IN_DOCKER = 'RUN_IN_DOCKER'
TRUE_VALUE = 'yes'
USERNAME_MAX_LENGTH = 150
EMAIL_MAX_LENGTH = 255
PHONE_MAX_LENGTH = 50
PASSWORD_HASH_MAX_LENGTH = 255
TG_ID_MAX_LENGTH = 50
