from pathlib import Path

LOGS_DIR = Path("logs")
LOG_FILE = LOGS_DIR / "app.log"
LOG_MAX_BYTES = 10 * 1024 * 1024   # 10 МБ
LOG_BACKUP_COUNT = 10

CAFE_NAME_MAX_LENGTH = 255
CAFE_ADDRESS_MAX_LENGTH = 500
CAFE_PHONE_MAX_LENGTH = 50
